### ISSUE TITLE
Google+ Deprecation

### ISSUE THREAD

**Issue by gtebbutt** [passport-next/passport-google-oauth2#1]
The Google+ API is being deprecated in a couple of months, and since the original library looks to be unmaintained, I wanted to check if this fork is set up to use the alternative API? 

There's a PR on the original repo here with the (relatively small) fixes: jaredhanson/passport-google-oauth2#51 but from a quick glance it looks like the commit history between there and here is a little confusing!

**Comment by rwky** [comment]
This is a fork of a different repo that provides google auth however I checked and yes we use the plus api for profiles but oauth2 api for login. I'll fix and release a new version asap.

**Comment by gtebbutt** [comment]
Thanks for the quick follow up, very much appreciate it - I thought it was a (more or less) direct fork, as with the Facebook strategy, but I've looked at the tree in more detail now! 

Out of interest, is there a specific reason that this library is quite diverged from the original, but the passport-facebook one is a direct fork? As far as I can see, the goal here is more regular updates and maintenance, which is brilliant - I'm just trying to figure out the details before moving things across!

**Comment by rwky** [comment]
>Out of interest, is there a specific reason that this library is quite diverged from the original, but the passport-facebook one is a direct fork? As far as I can see, the goal here is more regular updates and maintenance, which is brilliant - I'm just trying to figure out the details before moving things across!

When forking the various repos I picked the ones I used in production and this one https://www.npmjs.com/package/passport-google-oauth2 https://github.com/mstade/passport-google-oauth2 is the one I used.

**Comment by gtebbutt** [comment]
Understood, that makes sense. It looks like the official library (https://www.npmjs.com/package/passport-google-oauth20) has about 10x the usage and has actually been updated somewhat more recently than that fork - assuming the goal for passport-next is to be a drop-in replacement for the original (evidently orphaned) repos, I wonder if starting from https://github.com/jaredhanson/passport-google-oauth2 might actually be easier here in the long run?

**Comment by rwky** [comment]
I'll take a look that one's not been updated in 3 years so will still need some love, I'll compare the two and merge things together. 

This isn't intended to be a drop-in replacement, there will be differences which will become greater as time goes on, the main focus of these forks is to work (a lot of the upstream ones simply don't work anymore) and to be maintained regularly.

For example this package will become incompatible with the upstream version once I fix the login since the plus profile provides more data than the google sign in profile, however it will continue to work once plus is shutdown where as the upstream one won't.

**Comment by gtebbutt** [comment]
All clear, thanks for explaining!

**Comment by rwky** [comment]
New version pushed to npm also did some linting fixes :)

**Comment by guyellis** [comment]
@rwky please can you add a version tag on master so the commit that matches the publish to npm is tagged here for future travelers: https://github.com/passport-next/passport-google-oauth2/releases

Thanks.

**Comment by rwky** [comment]
@guyellis ta! Forgot that I've pushed it now.
