### ISSUE TITLE
redirect after auth not setting client session properly

### ISSUE THREAD

**Issue by victorbadila** [passport-next/passport-google-oauth2#2]
Summary:
I implemented the solution accordingly to the example. In order to actually be able to use the fact that the user is authenticated I used session management (`express-session`). If the entry point of the app is different from the auth endpoint then everything works as expected, the app sets a session in memory and a session id on the browser and once the user is fetched from google then it becomes available on any subsequent request.

This does not always work if the first request that is made is to the auth endpoint (in the example in the readme file that would be `/auth/google`. The session is saved on the server, I was able to log that, however after the redirect it seems as if the browser didn't set any session cookie for the next requests. It only settles after a while. I suspect that there are some racing conditions between setting the cookie before redirect and the actual redirect.

Expected behavior:
After redirect all future browser requests will have the same sessionId.

Actual behavior:
After redirect future browser requests have different sessionIds. this happens approximately 1 of 5 times, in most tries the session gets persisted before the redirect happens.

Code:
There isn't anything special to put here, it's the exact same example as in the readme file.

Environment
* Operating System: Ubuntu 18.04
* Node version: node v.10
* passport version: 0.4.0
* passport-google-oauth2 version: 1.0.0

**Comment by rwky** [comment]
Can you please try with the latest version of passport-next/passport instead of passport 0.4.0. If that doesn't help can you please provide the code (secrets omitted obviously).

**Comment by victorbadila** [comment]
It seems the problem I was facing was in regards to middleware loading. Somehow setting up routes which return static files AFTER the auth parts are set up leads to the problems I mentioned some of the times. I am going to close this. In case it matters this is the part which sums it up and helped me fix things: https://stackoverflow.com/a/22524566/3216791

I'm going to close the issue now.
